### ISSUE TITLE
DMD Compiler errors

### ISSUE THREAD

**Issue by ghost** [pwil3058/dunnart#1]
Digital Mars DMD compiler v2.073.2.
On make I have some deprication warnings and two errors:
ddlib\lexan.d(270): Error: cannot implicitly convert expression (lits[target[cast(uint)index]].lexeme_index) of type long to uint
ddlib\lexan.d(408): Error: template instance ddlib.lexan.LiteralMatcher!(DDHandle) error instantiating
ddlib\templates.d(40):        instantiated from here: LexicalAnalyser!(DDHandle, Regex!char)
make: *** [ddpg_bootstrap] Error 1

**Comment by pwil3058** [comment]
I get no errors but I do get the deprecation warnings for std.algorithm.sort.

A quick look at the documentation for std.algorithm.sort indicates that it is very complicated and fixing this issue will take more of my time than I have available at this time so I'll leave this issue open for the foreseeable future.

**Comment by pwil3058** [comment]
Simple work around for deprecation of dynamic array "sort" property implemented.
